# Generated by Django 3.2.8 on 2023-11-17 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_auto_20231117_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 1, 31, 30, 840366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 1, 31, 30, 841524, tzinfo=utc)),
        ),
    ]
