# Generated by Django 3.2.8 on 2023-12-01 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0014_auto_20231121_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 1, 20, 21, 267723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 1, 20, 21, 269128, tzinfo=utc)),
        ),
    ]
