# Generated by Django 3.2.8 on 2023-12-01 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0015_auto_20231201_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 1, 22, 27, 464204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 1, 22, 27, 465254, tzinfo=utc)),
        ),
    ]
