# Generated by Django 3.2.8 on 2024-01-10 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0017_auto_20240110_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='log_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 0, 44, 23, 361993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 0, 44, 23, 363019, tzinfo=utc)),
        ),
    ]
