# Generated by Django 3.2.8 on 2024-01-10 01:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0018_auto_20240110_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spend',
            name='log_number',
        ),
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 1, 1, 34, 44586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 1, 1, 34, 45869, tzinfo=utc)),
        ),
    ]
