# Generated by Django 3.2.8 on 2024-01-31 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0020_auto_20240128_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 38, 16, 56108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 38, 16, 57051, tzinfo=utc)),
        ),
    ]
