# Generated by Django 3.2.8 on 2024-02-01 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0021_auto_20240131_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 11, 37, 9, 894614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 11, 37, 9, 895501, tzinfo=utc)),
        ),
    ]
