# Generated by Django 3.2.8 on 2024-07-22 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0023_auto_20240201_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='url',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 15, 10, 34, 492586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 15, 10, 34, 506103, tzinfo=utc)),
        ),
    ]
