# Generated by Django 3.2.8 on 2024-07-25 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0024_auto_20240722_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 25, 11, 13, 12, 472714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 25, 11, 13, 12, 473985, tzinfo=utc)),
        ),
    ]
