# Generated by Django 3.2.8 on 2024-07-28 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0027_auto_20240725_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 17, 15, 40, 808634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 17, 15, 40, 810084, tzinfo=utc)),
        ),
    ]
