# Generated by Django 3.2.8 on 2024-12-22 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depenses', '0028_auto_20240728_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='other_spend_reason',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='spend_type',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='way_of_payment',
        ),
        migrations.AddField(
            model_name='spend',
            name='approved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spend',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 13, 16, 34, 964745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='status',
            field=models.TextField(choices=[('INITIAL', 'INITIAL'), ('SUP_VALIDATION', 'SUP_VALIDATION'), ('DIR_VALIDATION', 'DIR_VALIDATION'), ('Non confirmé', 'Non confirmé'), ('Confirmé', 'Confirmé')], default='INITIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 13, 16, 34, 965958, tzinfo=utc)),
        ),
    ]
