# Generated by Django 3.2.8 on 2024-12-24 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0032_auto_20241222_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 13, 42, 8, 882264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spendcomment',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 13, 42, 8, 883188, tzinfo=utc)),
        ),
    ]
