# Generated by Django 3.2.8 on 2022-07-12 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
