# Generated by Django 3.2.8 on 2022-07-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20220715_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancomment',
            options={},
        ),
    ]
