# Generated by Django 3.2.8 on 2022-08-20 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('plans', '0005_alter_plancomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-day']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='added',
        ),
        migrations.AddField(
            model_name='plan',
            name='communes',
            field=models.ManyToManyField(to='regions.Commune'),
        ),
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 0, 0)),
            preserve_default=False,
        ),
    ]
