# Generated by Django 3.2.8 on 2022-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20220820_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
    ]
