# Generated by Django 3.2.8 on 2022-08-20 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_updatable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='plancomment',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
