# Generated by Django 3.2.8 on 2022-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20220820_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='isfree',
            field=models.BooleanField(default=False),
        ),
    ]
