# Generated by Django 3.2.8 on 2022-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_auto_20220829_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='plantask',
            unique_together={('plan', 'order')},
        ),
    ]
