# Generated by Django 3.2.8 on 2022-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_auto_20220829_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
