# Generated by Django 3.2.8 on 2022-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_auto_20220830_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='client_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='commune_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tasks_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
