# Generated by Django 3.2.8 on 2022-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0019_remove_medecin_ismedical'),
        ('regions', '0001_initial'),
        ('plans', '0017_auto_20220901_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='clients',
            field=models.ManyToManyField(blank=True, to='medecins.Medecin'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='communes',
            field=models.ManyToManyField(blank=True, to='regions.Commune'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='valid_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='valid_commune',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='valid_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
