# Generated by Django 3.2.8 on 2022-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_auto_20221126_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='client_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='commune_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tasks_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
