# Generated by Django 3.2.8 on 2024-10-08 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_auto_20241008_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='transferred_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
