# Generated by Django 3.2.8 on 2023-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0023_auto_20231206_1703'),
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='medecin',
        ),
        migrations.AddField(
            model_name='deal',
            name='medecin',
            field=models.ManyToManyField(blank=True, related_name='medecins', to='medecins.Medecin'),
        ),
    ]
