# Generated by Django 3.2.8 on 2024-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0024_alter_medecin_specialite'),
        ('deals', '0003_auto_20231213_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='medecin',
            field=models.ManyToManyField(blank=True, related_name='medecin', to='medecins.Medecin'),
        ),
    ]
