# Generated by Django 3.2.8 on 2024-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='cost',
            field=models.CharField(max_length=255),
        ),
    ]
