# Generated by Django 3.2.8 on 2024-11-27 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0009_délégue_representant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Délégue_Representant',
            new_name='Delegue_Representant',
        ),
    ]
