# Generated by Django 3.2.8 on 2024-11-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_rename_délégue_representant_delegue_representant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegue_Representant',
        ),
    ]
