# Generated by Django 3.2.8 on 2023-11-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('regions', '0002_wilaya_code_name'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertargetmonthproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='usertargetmonthproduct',
            name='usermonth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.usertargetmonth'),
        ),
        migrations.AddField(
            model_name='usertargetmonth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersourceproduct',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='ordersourceproduct',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ordersource'),
        ),
        migrations.AddField(
            model_name='ordersource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='ordersource',
            name='source_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.source'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='clients.OrderProduct', to='produits.Produit'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ordersource'),
        ),
        migrations.AddField(
            model_name='monthcomment',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthcomment',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Client Supérieur'),
        ),
        migrations.AddField(
            model_name='client',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.wilaya'),
        ),
        migrations.AlterUniqueTogether(
            name='usertargetmonth',
            unique_together={('user', 'date')},
        ),
    ]
