# Generated by Django 3.2.8 on 2023-11-17 01:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0002_wilaya_code_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ffile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Target Quantity')),
            ],
            options={
                'verbose_name': 'Product Target',
                'verbose_name_plural': 'Products Target',
            },
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('lilium_Pharma', 'Lilium Pharma'), ('lilium1', 'Lilium1'), ('lilium2', 'Lilium2'), ('orient', 'Orient'), ('administration', 'Administration')], default='lilium1', max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=10, null='True')),
                ('adresse', models.CharField(default='alger', max_length=325)),
                ('activate', models.CharField(blank=True, max_length=255, null=True, unique='True')),
                ('rolee', models.CharField(choices=[('Commercial', 'Commercial'), ('Superviseur', 'Superviseur'), ('CountryManager', 'Countrymanager')], default='Commercial', max_length=35)),
                ('speciality_rolee', models.CharField(choices=[('Medico_commercial', 'Medico Commercial'), ('Commercial', 'Commercial'), ('Superviseur_regional', 'Superviseur Regional'), ('Superviseur_national', 'Superviseur National'), ('Superviseur', 'Superviseur'), ('CountryManager', 'Countrymanager'), ('Admin', 'Admin'), ('Office', 'Office')], default='Commercial', max_length=35)),
                ('can_add_medecin', models.BooleanField(default=False)),
                ('can_update_medecin', models.BooleanField(default=False)),
                ('can_add_client', models.BooleanField(default=False)),
                ('can_view_visites', models.BooleanField(default=False)),
                ('notification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ios_notification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('recive_mail', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('femme', 'Femme')], default='Homme', max_length=15)),
                ('CNAS', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateField(default=datetime.date(2023, 11, 17))),
                ('conge', models.FloatField(default=0, max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(choices=[('celibataire', 'Celibataire'), ('marrié', 'Maried')], default='celibataire', max_length=15)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='', verbose_name='scanned contract')),
                ('hidden', models.BooleanField(default=False)),
                ('work_as_commercial', models.BooleanField(default=False)),
                ('commune', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='regions.commune')),
                ('sectors', models.ManyToManyField(blank=True, null=True, to='regions.Wilaya')),
                ('user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usersunder', models.ManyToManyField(blank=True, related_name='under', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
