# Generated by Django 3.2.8 on 2023-11-19 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('lilium', 'Lilium'), ('orient', 'Orient'), ('aniya', 'Aniya')], default='lilium', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
    ]
