# Generated by Django 3.2.8 on 2023-11-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231119_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('lilium pharma', 'Lilium Pharma'), ('orient bio', 'Orient Bio'), ('aniya pharma', 'Aniya Pharm'), ('all', 'All ')], default='lilium pharma', max_length=40),
        ),
    ]
