# Generated by Django 3.2.8 on 2023-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231120_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('lilium pharma', 'Lilium Pharma'), ('orient bio', 'Orient Bio'), ('aniya pharma', 'Aniya Pharm'), ('all', 'All ')], default='lilium pharma', max_length=40, verbose_name='Employee of'),
        ),
    ]
