# Generated by Django 3.2.8 on 2024-01-21 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_contrat',
            field=models.CharField(blank=True, choices=[('CDD', 'Cdd'), ('CDI', 'Cdi')], default='CDD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code_section',
            field=models.CharField(blank=True, choices=[('MED', 'Med'), ('ADMIN', 'Admin'), ('COM', 'Com')], default='MED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 1, 21)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium_Pharma', 'Lilium Pharma'), ('lilium1', 'Lilium1'), ('lilium2', 'Lilium2'), ('orient', 'Orient'), ('Aniya_Pharm', 'Aniya Pharm'), ('administration', 'Administration')], default='lilium1', max_length=40),
        ),
    ]
