# Generated by Django 3.2.8 on 2024-01-28 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240123_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 1, 28)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium Pharma', 'Lilium Pharma'), ('Lilium1', 'Lilium1'), ('Lilium2', 'Lilium2'), ('orient Bio', 'Orient'), ('Aniya_Pharm', 'Aniya Pharm'), ('Administration', 'Administration')], default='Lilium1', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speciality_rolee',
            field=models.CharField(choices=[('Medico_commercial', 'Medico Commercial'), ('Commercial', 'Commercial'), ('Superviseur_regional', 'Superviseur Regional'), ('Superviseur_national', 'Superviseur National'), ('Superviseur', 'Superviseur'), ('CountryManager', 'Countrymanager'), ('Admin', 'Admin'), ('Office', 'Office'), ('chargé_de_communication', 'Chargé De Communication'), ('gestionnaire_de_stock', 'Gestionnaire De Stock'), ('Finance_et_comptabilité', 'Finance Et Comptabilité')], default='Commercial', max_length=35),
        ),
    ]
