# Generated by Django 3.2.8 on 2024-01-31 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240128_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 1, 31)),
        ),
    ]
