# Generated by Django 3.2.8 on 2024-07-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 7, 28)),
        ),
    ]
