# Generated by Django 3.2.8 on 2024-08-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pc_paie_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 8, 13)),
        ),
    ]
