# Generated by Django 3.2.8 on 2024-08-13 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20240813_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pc_paie_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid numeric value.')]),
        ),
    ]
