# Generated by Django 3.2.8 on 2024-09-25 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_pc_paie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('lilium pharma', 'Lilium Pharma'), ('production', 'Production'), ('orient bio', 'Orient Bio'), ('aniya pharma', 'Aniya Pharm'), ('all', 'All ')], default='lilium pharma', max_length=40, verbose_name='Employee of'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 25)),
        ),
    ]
