# Generated by Django 3.2.8 on 2024-10-09 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20240925_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium Pharma', 'Lilium Pharma'), ('Lilium1', 'Lilium1'), ('Lilium2', 'Lilium2'), ('orient Bio', 'Orient'), ('Aniya_Pharm', 'Aniya Pharm'), ('production', 'Production'), ('Administration', 'Administration')], default='Lilium1', max_length=40),
        ),
        migrations.CreateModel(
            name='UserNotificationPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_receive_notification_comment', models.BooleanField(default=True)),
                ('can_receive_notification_validation_planning', models.BooleanField(default=True)),
                ('can_receive_notification_bon_commande', models.BooleanField(default=True)),
                ('can_receive_notification_bon_sortie', models.BooleanField(default=True)),
                ('can_receive_notification_versement', models.BooleanField(default=True)),
                ('can_receive_notification_evaluation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
