# Generated by Django 3.2.8 on 2024-10-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20241009_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationpermissions',
            options={'verbose_name_plural': 'Notification'},
        ),
    ]
