# Generated by Django 3.2.8 on 2024-10-10 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_usernotificationpermissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_receive_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
    ]
