# Generated by Django 3.2.8 on 2024-10-28 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20241014_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 10, 28)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium Pharma', 'Lilium Pharma'), ('Lilium 1', 'Lilium1'), ('Lilium 2', 'Lilium2'), ('orient Bio', 'Orient'), ('Aniya_Pharm', 'Aniya Pharm'), ('production', 'Production'), ('Administration', 'Administration')], default='Lilium 1', max_length=40),
        ),
    ]
