# Generated by Django 3.2.8 on 2024-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20241028_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium_Pharma', 'Lilium Pharma'), ('lilium1', 'Lilium1'), ('lilium2', 'Lilium2'), ('orient Bio', 'Orient'), ('aniya_Pharm', 'Aniya Pharm'), ('production', 'Production'), ('administration', 'Administration')], default='lilium1', max_length=40),
        ),
    ]
