# Generated by Django 3.2.8 on 2024-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userprofile_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(choices=[('lilium Pharma', 'Lilium Pharma'), ('Lilium1', 'Lilium1'), ('Lilium2', 'Lilium2'), ('orient Bio', 'Orient'), ('Aniya_Pharm', 'Aniya Pharm'), ('production', 'Production'), ('Administration', 'Administration')], default='Lilium1', max_length=40),
        ),
    ]
