# Generated by Django 3.2.8 on 2024-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20241112_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='cans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='code_contrat',
            field=models.CharField(blank=True, choices=[('CDD', 'Cdd'), ('CDI', 'Cdi')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='code_section',
            field=models.CharField(blank=True, choices=[('MED', 'Med'), ('ADMIN', 'Admin'), ('COM', 'Com')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('femme', 'Femme')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='pc_paie_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='situation',
            field=models.CharField(blank=True, choices=[('celibataire', 'Celibataire'), ('marrié', 'Maried')], max_length=15, null=True),
        ),
    ]
