# Generated by Django 3.0.6 on 2020-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_remove_medecin_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='classification',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], default='c', max_length=15),
        ),
    ]
