# Generated by Django 3.0.6 on 2020-08-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0007_medecin_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
    ]
