# Generated by Django 3.0.6 on 2020-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0009_medecin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='updatable',
            field=models.BooleanField(default=True),
        ),
    ]
