# Generated by Django 3.2.8 on 2023-11-17 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(default=datetime.datetime(2023, 11, 17, 1, 9, 18, 768662, tzinfo=utc))),
                ('societe', models.CharField(max_length=100)),
                ('representant', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=50, null=True)),
                ('numero_de_telephone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('activite', models.CharField(max_length=100)),
                ('famille', models.TextField(choices=[('detaillant', 'detaillant'), ('grossistes', 'Grossistes'), ('Super grossistes', 'Super grossistes')], default='detaillant', max_length=40)),
                ('mode_de_reglement', models.TextField(choices=[('virement_bancaire', 'virement_bancaire'), ('chéque', 'chéque'), ('espece', 'espece')], max_length=40)),
                ('pays', models.TextField(choices=[('Algerie', 'Algerie'), ('Tunisie', 'Tunisie'), ('Jordanie', 'Jordanie'), ('Usa', 'Usa')], default='Algerie', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.CharField(max_length=100)),
                ('id_fiscal', models.CharField(max_length=100)),
                ('compte_bancaire', models.CharField(max_length=100)),
                ('compte_comptable', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=100)),
                ('rib', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=100)),
                ('banque', models.CharField(max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
            ],
        ),
    ]
