# Generated by Django 3.2.8 on 2023-11-17 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 1, 11, 48, 472755, tzinfo=utc)),
        ),
    ]
