# Generated by Django 3.2.8 on 2023-11-17 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 1, 12, 49, 892093, tzinfo=utc)),
        ),
    ]
