# Generated by Django 3.2.8 on 2023-11-17 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0008_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 2, 19, 36, 686822, tzinfo=utc)),
        ),
    ]
