# Generated by Django 3.2.8 on 2023-12-01 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0014_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 1, 22, 27, 466667, tzinfo=utc)),
        ),
    ]
