# Generated by Django 3.2.8 on 2024-01-31 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0016_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 38, 16, 58298, tzinfo=utc)),
        ),
    ]
