# Generated by Django 3.2.8 on 2024-07-28 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0019_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 17, 15, 40, 812156, tzinfo=utc)),
        ),
    ]
