# Generated by Django 3.2.8 on 2024-10-10 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0033_productinactiveingredients_e_num'),
        ('fournisseurs', '0020_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 10, 10, 20, 27, 58, 134344, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(' matiere_premiere', 'Matiere Premiere'), (' semi finish product', 'Semi Finish Product'), (' primary packaging', 'Primary Packaging'), (' secondary packaging', 'Secondary Packaging')], max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('product', models.ManyToManyField(blank=True, to='produits.Produit')),
            ],
        ),
    ]
