# Generated by Django 3.2.8 on 2024-10-10 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0022_auto_20241010_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('unit', 'Unit')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 10, 10, 20, 55, 23, 595202, tzinfo=utc)),
        ),
    ]
