# Generated by Django 3.2.8 on 2024-10-10 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0023_auto_20241010_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 10, 10, 21, 27, 34, 39904, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('unit', 'Unit')], default='unit', max_length=10)),
                ('destination', models.CharField(choices=[('autre_usine', 'Autre Usine'), ('endomage', 'Endomage'), ('destination', 'Destination')], default='destination', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.item')),
            ],
        ),
    ]
