# Generated by Django 3.2.8 on 2024-11-27 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0024_auto_20241010_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 21, 44, 14, 979749, tzinfo=utc)),
        ),
    ]
