# Generated by Django 3.2.8 on 2024-12-24 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0027_alter_fournisseur_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 13, 42, 8, 885167, tzinfo=utc)),
        ),
    ]
