# Generated by Django 3.2.8 on 2023-11-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leaves.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved', models.CharField(choices=[('WAITING', 'Waiting'), ('REFUSED', 'Refused'), ('ACCEPTED', 'Accepted')], default='WAITING', max_length=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('attachement', models.FileField(blank=True, null=True, upload_to=leaves.models.get_leave_upload_path)),
                ('added', models.DateField(default=django.utils.timezone.now)),
                ('approval_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_user', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('approved', models.CharField(choices=[('WAITING', 'Waiting'), ('REFUSED', 'Refused'), ('ACCEPTED', 'Accepted')], default='WAITING', max_length=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('attachement', models.FileField(blank=True, null=True, upload_to=leaves.models.get_absence_upload_path)),
                ('attachement_upload_date', models.DateTimeField(blank=True, null=True)),
                ('added', models.DateField(default=django.utils.timezone.now)),
                ('absence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.absencetype')),
                ('approval_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_approval_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userproxy')),
            ],
            options={
                'permissions': [('approve_absence', 'Can decide whether the absence is accepted or refused')],
            },
        ),
    ]
