# Generated by Django 3.2.8 on 2023-06-16 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('q1', models.PositiveIntegerField()),
                ('q2', models.TextField(max_length=200)),
                ('q3', models.TextField(max_length=200)),
                ('q4', models.TextField(max_length=200)),
                ('q5', models.TextField(max_length=200)),
                ('q6', models.TextField(max_length=200)),
                ('q7', models.TextField(max_length=200)),
                ('q8', models.TextField(max_length=200)),
                ('q9', models.TextField(max_length=200)),
                ('q10', models.TextField(max_length=200)),
                ('can_update', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
