# Generated by Django 3.2.8 on 2023-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q10',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q4',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q5',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q6',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q7',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q8',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q9',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
