# Generated by Django 3.2.8 on 2023-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0002_auto_20230617_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q9',
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q10a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q10b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q2a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q3a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q4a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q4b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q5b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q6a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q6b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q7a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q7b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q8a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q8b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q9a',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q9b',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
