# Generated by Django 3.2.8 on 2023-06-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0003_auto_20230618_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q10a',
            new_name='q10',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q10b',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q2a',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q3a',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q4a',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q4b',
            new_name='q6',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q5b',
            new_name='q7',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q6a',
            new_name='q8',
        ),
        migrations.RenameField(
            model_name='monthly_evaluation',
            old_name='q6b',
            new_name='q9',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q7a',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q7b',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q8a',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q8b',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q9a',
        ),
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q9b',
        ),
    ]
