# Generated by Django 3.2.8 on 2023-06-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0004_auto_20230624_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
