# Generated by Django 3.2.8 on 2023-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0005_auto_20230625_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Combien de médecins visites au cours du mois?'),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q10',
            field=models.TextField(blank=True, null=True, verbose_name="Écrivez cinq médecins que vous souhaitez gagner afin qu'ils puissent écrire vos produits pour vous car ils ont de nombreux patients, le nom du médecin et le produit"),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q2',
            field=models.TextField(blank=True, null=True, verbose_name="Qui sont les médecins qui ont été visités plus d'une fois ce mois-ci, et la raison?"),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q3',
            field=models.TextField(blank=True, null=True, verbose_name="Combien de médecins n'ont pas été visités ce mois-ci, en mentionnant le nom du médecin et la raison de la non-visite ?"),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q4',
            field=models.TextField(blank=True, null=True, verbose_name='Qui sont les médecins visités ce mois-ci avec Superviseur et quel est le but de la visite ?'),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q5',
            field=models.TextField(blank=True, null=True, verbose_name='Écrivez cinq médecins importants en ecriture pour chaque produit'),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q6',
            field=models.TextField(blank=True, null=True, verbose_name="Mentionnez 10 médecins qui ont visité plus de trois visites et n'ont pas encore écrit, en expliquant la raison à votre avis"),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q7',
            field=models.TextField(blank=True, null=True, verbose_name='Quels plus avez-vous apporté avec les médecins ce mois-ci, en mentionnant le nom du médecin et le type du plus'),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q8',
            field=models.TextField(blank=True, null=True, verbose_name='Quels sont les médecins que vous suggérez de retirer de la liste, en mentionnant la raison'),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q9',
            field=models.TextField(blank=True, null=True, verbose_name="Quelles sont vos suggestions pour les médecins qui sont visités régulièrement et qui n'écrivent pas encore bien. Mentionner le nom du médecin et la suggestion"),
        ),
    ]
