# Generated by Django 3.2.8 on 2023-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0006_auto_20230625_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='q2',
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='q1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Combien de médecins visités au cours du mois?'),
        ),
    ]
