# Generated by Django 3.2.8 on 2023-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0009_alter_monthly_evaluation_q2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_evaluation',
            name='can_update',
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q11',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Combien de pharmacies et de grossistes avez vous visités au cours du mois ?'),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q12',
            field=models.TextField(blank=True, null=True, verbose_name='Combien de super grossistes avez vous visité ce mois-ci, en mentionnant le nom du super grossistes et la raison de la visite'),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q13',
            field=models.TextField(blank=True, null=True, verbose_name='Combien de bon de commandes durant ce mois, en mentionnant le nom du client, le produit et la quantité'),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='q14',
            field=models.TextField(blank=True, null=True, verbose_name='Quelles sont vos suggestions pour améliorer les ventes'),
        ),
    ]
