# Generated by Django 3.2.8 on 2024-02-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthly_evaluations', '0012_monthly_evaluation_q15'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(max_length=200, verbose_name='Note')),
                ('perc', models.CharField(max_length=200, verbose_name='Pourcentage')),
                ('q1', models.BooleanField(default=False, verbose_name='Connaissance pathologie et motif de prescription')),
                ('q2', models.BooleanField(default=False, verbose_name='Connaissance des Caractéristiques produit')),
                ('q3', models.BooleanField(default=False, verbose_name="Connaissance des mécanismes d'action")),
                ('q4', models.BooleanField(default=False, verbose_name='Connaissance études, donnes et références scientifiques ')),
                ('q5', models.BooleanField(default=False, verbose_name='Positionnement produit vis-à-vis les concurrents ')),
                ('q6', models.BooleanField(default=False, verbose_name='Ratio spécialités ciblée / le nombre globale des medecins ')),
                ('q7', models.BooleanField(default=False, verbose_name='Ratio nombre des potentiels A/  le nombre globale des medecins')),
                ('q8', models.BooleanField(default=False, verbose_name='Informations medecins (contact, spécialité, potentialité, adresse et adresse mail)')),
                ('q9', models.BooleanField(default=False, verbose_name='cycles des visites\xa0(nombre de visites par medecins, durée entre 2 visites)')),
                ('q10', models.BooleanField(default=False, verbose_name='Couverture secteur')),
                ('q11', models.BooleanField(default=False, verbose_name='Communication et adaptation des types de présentations au profil du médecin')),
                ('q12', models.BooleanField(default=False, verbose_name='Préparation avant la visite (fiche médecin)')),
                ('q13', models.BooleanField(default=False, verbose_name='\xa0Traitement des objections medecins')),
                ('q14', models.BooleanField(default=False, verbose_name="\xa0Traitement des d'objections pharmaciens")),
                ('q15', models.BooleanField(default=False, verbose_name='Gestion de temps')),
                ('q16', models.BooleanField(default=False, verbose_name='Ciblage medecins spécialités')),
                ('q17', models.BooleanField(default=False, verbose_name='Ciblage medecins potentialités')),
                ('q18', models.BooleanField(default=False, verbose_name='Ciblage secteur')),
                ('q19', models.BooleanField(default=False, verbose_name='Planning hebdomadaire')),
                ('q20', models.BooleanField(default=False, verbose_name="timing d'introduction")),
                ('q21', models.BooleanField(default=False, verbose_name='Nombre des présentations/ produit')),
                ('q22', models.BooleanField(default=False, verbose_name='Informations récoltées Medecins')),
                ('q23', models.BooleanField(default=False, verbose_name='Informations récoltées pharmacies (état de stock + medecins prescripteurs)')),
                ('q24', models.BooleanField(default=False, verbose_name='Conformité des griffes de passages (date + clarté)')),
                ('q25', models.BooleanField(default=False, verbose_name="Timing d'introduction")),
                ('q26', models.BooleanField(default=False, verbose_name='Engagement et Intégrité')),
                ('q27', models.BooleanField(default=False, verbose_name='Confidentialité')),
                ('q28', models.BooleanField(default=False, verbose_name='Transparence')),
                ('q29', models.BooleanField(default=False, verbose_name="Conflits d'intérêts")),
                ('q30', models.BooleanField(default=False, verbose_name='Relations avec les professionnels de la santé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
