# Generated by Django 3.2.8 on 2024-02-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0013_supevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supevaluation',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='supevaluation',
            name='perc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pourcentage'),
        ),
    ]
