# Generated by Django 3.2.8 on 2024-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0014_auto_20240203_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_evaluation',
            name='sup_evaluation',
            field=models.BooleanField(default=False, verbose_name='Le superviseur à fait votre évaluation'),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='user_sup_evaluation',
            field=models.BooleanField(default=True, verbose_name='Le délégué a évalué son superviseur'),
        ),
    ]
