# Generated by Django 3.2.8 on 2024-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0016_alter_monthly_evaluation_sup_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_evaluation',
            name='user_direction_evaluation',
            field=models.BooleanField(default=False, verbose_name="La direction à consulté l'évaluation"),
        ),
        migrations.AlterField(
            model_name='monthly_evaluation',
            name='user_sup_evaluation',
            field=models.BooleanField(default=True, verbose_name='Le délégué à évalué son superviseur'),
        ),
    ]
