# Generated by Django 3.2.8 on 2024-03-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthly_evaluations', '0017_auto_20240315_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupEvaluationToDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('q1', models.TextField(blank=True, null=True, verbose_name='Avis du Superviseur sur la directrice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
