# Generated by Django 3.2.8 on 2024-03-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0018_supevaluationtodirection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthly_evaluation',
            options={'verbose_name': 'Delegate Evaluation'},
        ),
        migrations.AlterModelOptions(
            name='supevaluation',
            options={'verbose_name': 'Supervisor to Delegate'},
        ),
        migrations.AlterModelOptions(
            name='supevaluationtodirection',
            options={'verbose_name': 'Supervisor to Direction'},
        ),
        migrations.AddField(
            model_name='supevaluationtodirection',
            name='direction_evaluate_sup',
            field=models.BooleanField(default=False, verbose_name="la direction à fait l'évaluation du superviseur"),
        ),
        migrations.AddField(
            model_name='supevaluationtodirection',
            name='sup_evaluate_direction',
            field=models.BooleanField(default=True, verbose_name="Le superviseur à fait l'évaluation de la direction"),
        ),
    ]
