# Generated by Django 3.2.8 on 2024-03-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthly_evaluations', '0019_auto_20240316_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionEvaluationToSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('direction_evaluate_sup', models.BooleanField(default=True, verbose_name="la direction à fait l'évaluation du superviseur")),
                ('q1', models.TextField(blank=True, null=True, verbose_name='Avis de la direction sur le superviseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direction to Supervisor',
            },
        ),
    ]
