# Generated by Django 3.2.8 on 2024-03-17 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monthly_evaluations', '0020_directionevaluationtosup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionToDelegateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('q1', models.BooleanField(default=False, verbose_name="Êtes-vous d'accord avec l'évaluation du superviseur sur le délégué ?")),
                ('explication', models.CharField(blank=True, max_length=1000, null=True, verbose_name='explication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direction To Delegate Evaluation',
            },
        ),
    ]
