# Generated by Django 3.2.8 on 2024-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0021_directiontodelegateevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiontodelegateevaluation',
            name='q1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Êtes-vous d'accord avec l'évaluation du superviseur sur le délégué ?"),
        ),
    ]
