# Generated by Django 3.2.8 on 2024-03-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0022_alter_directiontodelegateevaluation_q1'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionevaluationtosup',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directiontodelegateevaluation',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_evaluation',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supevaluation',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supevaluationtodirection',
            name='updatable',
            field=models.BooleanField(default=False),
        ),
    ]
