# Generated by Django 3.2.8 on 2024-04-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_evaluations', '0024_monthly_evaluation_own_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='supevaluation',
            name='probs',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='problémes'),
        ),
        migrations.AddField(
            model_name='supevaluation',
            name='responses_okay',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Le superviseur est d;accord avec les réponses du délégué ?'),
        ),
    ]
