# Generated by Django 3.2.8 on 2024-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220910_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='companys', verbose_name='Réglement intérieur'),
        ),
    ]
