# Generated by Django 3.2.8 on 2024-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
