# Generated by Django 3.2.8 on 2024-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_activité'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
