# Generated by Django 3.2.8 on 2023-11-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='المنتج المنافس')),
                ('company', models.CharField(max_length=255, null=True, verbose_name=' اسم الشركة المنافسة ')),
                ('country', models.CharField(max_length=255, null=True, verbose_name=' مكان الصنع ')),
                ('price', models.CharField(max_length=255, null=True, verbose_name=' السعر ')),
                ('treatment_duration', models.CharField(max_length=255, verbose_name=' مدة العلاج ')),
                ('marketing', models.CharField(choices=[('medical', 'medical'), ('commercial', 'commercial'), ('medicocommercial', 'medicocommercial')], max_length=255, verbose_name=' طريقة التسويق المعتمدة ')),
                ('good', models.TextField(null=True, verbose_name=' نقاط القوة ')),
                ('bad', models.TextField(null=True, verbose_name=' نقاط الضعف  ')),
                ('observations', models.TextField(null=True, verbose_name=' ملاحظات ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('brochure', models.ImageField(blank=True, null=True, upload_to='')),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
