# Generated by Django 3.2.8 on 2023-11-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('concurents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='lilium_product'),
        ),
        migrations.AddField(
            model_name='cproduct',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concurents.shape', verbose_name=' الشكل الصيدلاني '),
        ),
        migrations.AddField(
            model_name='cproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concurents.cproduct'),
        ),
    ]
