# Generated by Django 3.2.8 on 2024-02-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('date_meet', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
