# Generated by Django 3.2.8 on 2024-02-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='heure_debut',
            field=models.TimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Heure De Début De La Réunion'),
        ),
        migrations.AddField(
            model_name='meet',
            name='heure_fin',
            field=models.TimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Heure De Fin De La Réunion'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='added',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Date De création'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meet',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Date De La Réunion'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
