# Generated by Django 3.2.8 on 2024-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20240214_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titre'),
        ),
    ]
