# Generated by Django 3.2.8 on 2024-01-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versement',
            name='numero_de_cheque',
        ),
    ]
