# Generated by Django 3.2.8 on 2024-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0005_versement_numero_de_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versement',
            name='en_reglement',
        ),
        migrations.AlterField(
            model_name='versement',
            name='recu',
            field=models.CharField(max_length=200, verbose_name='Client'),
        ),
    ]
