# Generated by Django 3.2.8 on 2024-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0006_auto_20240125_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versement',
            name='attachement',
            field=models.FileField(max_length=255, upload_to='versements', verbose_name='Piéce jointe'),
        ),
    ]
