# Generated by Django 3.2.8 on 2024-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0007_alter_versement_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versement',
            name='attachement',
            field=models.FileField(max_length=255, null=True, upload_to='versements', verbose_name='Piéce jointe'),
        ),
    ]
