# Generated by Django 3.2.8 on 2024-01-29 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0010_versement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='date_document',
            field=models.DateField(blank=True, null=True, verbose_name='Date Document'),
        ),
        migrations.AddField(
            model_name='versement',
            name='num_recu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de Reçu'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ajout Versement"),
        ),
        migrations.AlterField(
            model_name='versement',
            name='way_of_payment',
            field=models.CharField(choices=[('Chéque', 'Cheque'), ('Virement Bancaire', 'Virement'), ('Espéce', 'Espece')], default='Chéque', max_length=35, verbose_name='Type de paiement'),
        ),
    ]
