# Generated by Django 3.2.8 on 2024-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0011_auto_20240129_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybookuser',
            name='page_actuelle',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Actuelle (NE PAS REMPLIR'),
        ),
        migrations.AddField(
            model_name='paybookuser',
            name='page_debut',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la Première Page'),
        ),
        migrations.AddField(
            model_name='paybookuser',
            name='page_fin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de la Dérnière Page'),
        ),
        migrations.AlterField(
            model_name='paybookuser',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Numéro du Carnet'),
        ),
    ]
