# Generated by Django 3.2.8 on 2024-02-08 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0024_alter_medecin_specialite'),
        ('versement', '0014_creance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creance',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='creance',
            name='date_echeance',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date écheance'),
        ),
    ]
