# Generated by Django 3.2.8 on 2024-02-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versement', '0016_creance_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='creance',
            name='done',
        ),
    ]
