# Generated by Django 3.2.8 on 2024-04-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medecins', '0027_alter_medecin_telephone'),
        ('versement', '0018_versement_updatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versement',
            name='way_of_payment',
            field=models.CharField(choices=[('annulé', 'Annule'), ('Chéque', 'Cheque'), ('Virement Bancaire', 'Virement'), ('Espéce', 'Espece'), ('Espèce', 'Espèce')], default='Chéque', max_length=35, verbose_name='Type de paiement'),
        ),
        migrations.CreateModel(
            name='CreanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('attachement', models.FileField(blank=True, max_length=255, null=True, upload_to='versements', verbose_name='Piéce jointe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin', verbose_name='User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
