# Generated by Django 3.2.8 on 2024-05-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0027_alter_medecin_telephone'),
        ('versement', '0019_auto_20240415_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creanceclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin', verbose_name='Client'),
        ),
    ]
