# Generated by Django 3.2.8 on 2025-01-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début de déplacement')),
                ('end_date', models.DateField(verbose_name='Date de fin de déplacement')),
                ('nb_jours', models.PositiveIntegerField(verbose_name='Nombre de jours')),
                ('nb_nuits', models.PositiveIntegerField(verbose_name='Nombre de nuits')),
                ('wilaya1', models.CharField(max_length=100, verbose_name='Wilaya 1 (point de départ)')),
                ('wilaya2', models.CharField(max_length=100, verbose_name='Wilaya 2 (destination)')),
                ('distance', models.FloatField(verbose_name='Distance calculée (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Déplacement',
                'verbose_name_plural': 'Déplacements',
            },
        ),
    ]
