# Generated by Django 3.2.8 on 2025-01-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deplacement', '0002_nuitdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='deplacement',
            name='direction_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation direction'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='direction_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par la direction'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='fully_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation complète'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='fully_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé complètement par'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente'), ('supervisor_validated', 'Validé par le superviseur'), ('direction_validated', 'Validé par la direction'), ('validated', 'Validé')], default='waiting', max_length=50, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='supervisor_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation superviseur'),
        ),
        migrations.AddField(
            model_name='deplacement',
            name='supervisor_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par le superviseur'),
        ),
    ]
