# Generated by Django 3.2.8 on 2025-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0003_auto_20250114_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente'), ('validated_by_supervisor', 'Validé par le superviseur'), ('validated_by_direction', 'Validé par la direction'), ('Traité', 'Traité')], default='waiting', max_length=50, verbose_name='Statut'),
        ),
    ]
