# Generated by Django 3.0.6 on 2020-05-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('Généraliste', 'Generaliste'), ('Diabetologue', 'Diabetologue')], default='Généraliste', max_length=15)),
                ('classification', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], default='c', max_length=15)),
                ('telephone', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Commune')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
