# Generated by Django 3.0.6 on 2020-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='classification',
        ),
    ]
