# Generated by Django 3.0.6 on 2020-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0005_auto_20200611_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
