# Generated by Django 3.2.8 on 2022-08-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0013_auto_20211130_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
