# Generated by Django 3.2.8 on 2022-08-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0014_medecin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('Généraliste', 'Generaliste'), ('Diabetologue', 'Diabetologue'), ('Neurologue', 'Neurologue'), ('Psychologue', 'Psychologue'), ('Gynécologue', 'Gynecologue'), ('Rumathologue', 'Rumathologue'), ('Allergologue ', 'Allergologue'), ('Phtisio', 'Phtisio'), ('Cardiologue', 'Cardiologue'), ('Urologue', 'Urologue'), ('Hematologue', 'Hematologue'), ('Orthopedie', 'Orthopedie'), ('Nutritionist', 'Nutritionist'), ('Dermatologue', 'Dermatologue'), ('Interniste', 'Interniste'), ('Pharmacie', 'Pharmacie'), ('Grossiste', 'Grossiste'), ('SuperGros', 'Supergros'), ('Gastrologue', 'Gastrologue')], db_index=True, default='Généraliste', max_length=15),
        ),
    ]
