# Generated by Django 3.2.8 on 2022-08-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0015_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='ismedical',
            field=models.BooleanField(default=False),
        ),
    ]
