# Generated by Django 3.2.8 on 2022-08-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0016_medecin_ismedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecinSpecialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecinspecialite'),
        ),
    ]
