# Generated by Django 3.2.8 on 2022-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0017_auto_20220817_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinspecialite',
            name='ismedical',
            field=models.BooleanField(default=False),
        ),
    ]
