# Generated by Django 3.2.8 on 2022-08-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0018_medecinspecialite_ismedical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='ismedical',
        ),
    ]
