# Generated by Django 3.2.8 on 2023-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0019_remove_medecin_ismedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
