# Generated by Django 3.2.8 on 2023-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0022_auto_20231205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
