# Generated by Django 3.2.8 on 2024-03-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_wilaya_code_name'),
        ('medecins', '0024_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.wilaya'),
        ),
    ]
