# Generated by Django 3.2.8 on 2024-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0026_auto_20240314_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
