# Generated by Django 3.2.8 on 2024-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0027_alter_medecin_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='uploaded_from_excel',
            field=models.BooleanField(default=False),
        ),
    ]
