# Generated by Django 3.2.8 on 2024-12-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0028_medecin_uploaded_from_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('Généraliste', 'Generaliste'), ('Diabetologue', 'Diabetologue'), ('Neurologue', 'Neurologue'), ('Psychologue', 'Psychologue'), ('Gynécologue', 'Gynecologue'), ('Rumathologue', 'Rumathologue'), ('Allergologue ', 'Allergologue'), ('Phtisio', 'Phtisio'), ('Cardiologue', 'Cardiologue'), ('Urologue', 'Urologue'), ('Hematologue', 'Hematologue'), ('Orthopedie', 'Orthopedie'), ('Nutritionist', 'Nutritionist'), ('Dermatologue', 'Dermatologue'), ('Interniste', 'Interniste'), ('Pharmacie', 'Pharmacie'), ('Grossiste', 'Grossiste'), ('SuperGros', 'Supergros'), ('Gastrologue', 'Gastrologue'), ('Endocrinologue', 'Endocrinologue'), ('Dentiste', 'Dentiste'), ('ORL', 'Orl'), ('Maxilo facial', 'Maxilo Facial'), ('Sage Femme', 'Sage Femme'), ('Pediatre', 'Pediatre')], db_index=True, default='Généraliste', max_length=15),
        ),
    ]
