# Generated by Django 3.2.8 on 2023-11-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initial', 'initial'), ('traite', 'traite')], default='initial', max_length=20)),
                ('brochure', models.BooleanField(default=False)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('depot', models.CharField(choices=[('delegue', 'delegue'), ('principale', 'principale')], default='principale', max_length=20)),
            ],
            options={
                'verbose_name': 'Bon de sortie',
            },
        ),
        migrations.CreateModel(
            name='ExitOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initial', 'initial'), ('confirme', 'confirme'), ('en cours', 'en cours'), ('traite', 'traite')], default='initial', max_length=20)),
                ('flag', models.BooleanField(default=False)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('infos', models.CharField(blank=True, choices=[('yalidine', 'yalidine'), ('livreur', 'livreur'), ('bureau', 'bureau'), ('delegue', 'delegue')], max_length=255, null=True)),
                ('tracking', models.JSONField(blank=True, default=[])),
                ('bl', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('from_company', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bon de commande',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtt', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
