# Generated by Django 3.2.8 on 2024-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attente',
            field=models.BooleanField(default=False, verbose_name='En attente'),
        ),
    ]
