# Generated by Django 3.2.8 on 2024-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cause',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Cause Flag  |   سبب التعليق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Flag  |   طلبية معلقة'),
        ),
    ]
